version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client-boilerplate
    ports:
      - "3000:80"
    restart: always

  api:
    build: ./server-boilerplate
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_URL: mongodb+srv://srushtikhatale45_db_user:Srushtikhatale@cluster0.x2wxbvt.mongodb.net/?appName=Cluster0
    restart: always